export const FETCH_PHONES_START = 'FETCH_PHONES_START';
export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_FAIL = 'FETCH_PHONES_FAIL';
export const GET_PHONE_BY_ID = 'GET_PHONE_BY_ID';